java_binary(
    name = "closure_compiler",
    main_class = "com.google.javascript.jscomp.CommandLineRunner",
    runtime_deps = [
        "@closure_compiler_jar//jar",
    ],
    visibility = ["//visibility:public"],
)
    